# Base image for dependencies
FROM node:20.9.0-alpine AS base

WORKDIR /app

COPY package*.json .

# Development stage
FROM base AS dev

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]

# Build stage
FROM dev AS build

ARG NODE_ENV
ARG MONGODB_URI
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_BACKEND_DOMAIN
ARG NEXT_PUBLIC_BACKEND_API_DOMAIN
ARG NEXTAUTH_URI
ARG NEXTAUTH_URL

ENV NODE_ENV=${NODE_ENV}
ENV MONGODB_URI=${MONGODB_URI}
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV NEXT_PUBLIC_BACKEND_DOMAIN=${NEXT_PUBLIC_BACKEND_DOMAIN}
ENV NEXT_PUBLIC_BACKEND_API_DOMAIN=${NEXT_PUBLIC_BACKEND_API_DOMAIN}
ENV NEXTAUTH_URI=${NEXTAUTH_URI}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}

RUN npm run build

# Production stage
FROM node:20.9.0-alpine AS production

WORKDIR /app

COPY package*.json .

RUN --mount=type=cache,target=/app/.npm \
    npm set cache /app/.npm && \
    npm ci --only=production

COPY --from=build /app/.next ./.next

EXPOSE 3000

CMD ["npm", "start"]